require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaxReturnsController do

  # This should return the minimal set of attributes required to create a valid
  # TaxReturn. As you add validations to TaxReturn, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaxReturnsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tax_returns as @tax_returns" do
      tax_return = TaxReturn.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tax_returns).should eq([tax_return])
    end
  end

  describe "GET show" do
    it "assigns the requested tax_return as @tax_return" do
      tax_return = TaxReturn.create! valid_attributes
      get :show, {:id => tax_return.to_param}, valid_session
      assigns(:tax_return).should eq(tax_return)
    end
  end

  describe "GET new" do
    it "assigns a new tax_return as @tax_return" do
      get :new, {}, valid_session
      assigns(:tax_return).should be_a_new(TaxReturn)
    end
  end

  describe "GET edit" do
    it "assigns the requested tax_return as @tax_return" do
      tax_return = TaxReturn.create! valid_attributes
      get :edit, {:id => tax_return.to_param}, valid_session
      assigns(:tax_return).should eq(tax_return)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TaxReturn" do
        expect {
          post :create, {:tax_return => valid_attributes}, valid_session
        }.to change(TaxReturn, :count).by(1)
      end

      it "assigns a newly created tax_return as @tax_return" do
        post :create, {:tax_return => valid_attributes}, valid_session
        assigns(:tax_return).should be_a(TaxReturn)
        assigns(:tax_return).should be_persisted
      end

      it "redirects to the created tax_return" do
        post :create, {:tax_return => valid_attributes}, valid_session
        response.should redirect_to(TaxReturn.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tax_return as @tax_return" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaxReturn.any_instance.stub(:save).and_return(false)
        post :create, {:tax_return => {}}, valid_session
        assigns(:tax_return).should be_a_new(TaxReturn)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaxReturn.any_instance.stub(:save).and_return(false)
        post :create, {:tax_return => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tax_return" do
        tax_return = TaxReturn.create! valid_attributes
        # Assuming there are no other tax_returns in the database, this
        # specifies that the TaxReturn created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TaxReturn.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tax_return.to_param, :tax_return => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tax_return as @tax_return" do
        tax_return = TaxReturn.create! valid_attributes
        put :update, {:id => tax_return.to_param, :tax_return => valid_attributes}, valid_session
        assigns(:tax_return).should eq(tax_return)
      end

      it "redirects to the tax_return" do
        tax_return = TaxReturn.create! valid_attributes
        put :update, {:id => tax_return.to_param, :tax_return => valid_attributes}, valid_session
        response.should redirect_to(tax_return)
      end
    end

    describe "with invalid params" do
      it "assigns the tax_return as @tax_return" do
        tax_return = TaxReturn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaxReturn.any_instance.stub(:save).and_return(false)
        put :update, {:id => tax_return.to_param, :tax_return => {}}, valid_session
        assigns(:tax_return).should eq(tax_return)
      end

      it "re-renders the 'edit' template" do
        tax_return = TaxReturn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaxReturn.any_instance.stub(:save).and_return(false)
        put :update, {:id => tax_return.to_param, :tax_return => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tax_return" do
      tax_return = TaxReturn.create! valid_attributes
      expect {
        delete :destroy, {:id => tax_return.to_param}, valid_session
      }.to change(TaxReturn, :count).by(-1)
    end

    it "redirects to the tax_returns list" do
      tax_return = TaxReturn.create! valid_attributes
      delete :destroy, {:id => tax_return.to_param}, valid_session
      response.should redirect_to(tax_returns_url)
    end
  end

end
